name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ebefd629ccc1338a70af7e1e4c7cba0cb7ecbc7d9ea39d6aa436670f9607e16"

[versions]
minecraft = "1.21.1"
quilt = "0.26.4-beta.7"

[options]
acceptable-game-versions = ["1.21"]
