name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da361268b19e78dcdea49adb61704ae6595866fbeda9ec23b316fe35d732e55d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
