name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f9eaac9b3f847c27c477808b60ad01a4f67949ad2fdec0c85d2d0d081013ed2"

[versions]
fabric = "0.16.9"
minecraft = "1.21.3"

[options]
acceptable-game-versions = []
