name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df27e85163f42b1ff0d67d1e69f832343e96a92e5f50199cbb058fe1313b3842"

[versions]
minecraft = "1.21.1"
quilt = "0.26.3"

[options]
acceptable-game-versions = ["1.21"]
