name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29dd42f4ee6aa8924feefd880fbcf9e82480a08c083e1cf9b273302bed9c225f"

[versions]
minecraft = "1.21.1"
quilt = "0.26.4-beta.7"

[options]
acceptable-game-versions = ["1.21"]
