name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eddd592ddb964162eb8243b00f402c337a1130accb5456823fd78d01d77ec56"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
