name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee4e5a9e9f1044fc5a466cc10bc238e4171855bf2efb05500dd2b1a8805ae70f"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"

[options]
acceptable-game-versions = []
