name = "Ooc Server"
author = "MarioAndWeegee3"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db3638836a6d45c2cd3a5b6f9e5da18334ac6877ef43c2422afdf43790833ffb"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"

[options]
acceptable-game-versions = []
